import base64
import hashlib
import hmac
import io
import os
import threading
from typing import Any

from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel, Field

MODEL_ID = os.getenv("MODEL_ID", "segmind/tiny-sd")
IMAGE_API_KEY = os.getenv("IMAGE_API_KEY", "")
DEFAULT_STEPS = int(os.getenv("DEFAULT_STEPS", "12"))
MAX_STEPS = int(os.getenv("MAX_STEPS", "24"))
DEFAULT_WIDTH = int(os.getenv("DEFAULT_WIDTH", "512"))
DEFAULT_HEIGHT = int(os.getenv("DEFAULT_HEIGHT", "512"))
MAX_WIDTH = int(os.getenv("MAX_WIDTH", "768"))
MAX_HEIGHT = int(os.getenv("MAX_HEIGHT", "768"))

app = FastAPI(title="Game API Image Generation AI", version="1.0.0")

_pipe = None
_pipe_lock = threading.Lock()
_generation_lock = threading.Lock()


class Txt2ImgRequest(BaseModel):
    prompt: str = Field(min_length=1, max_length=2000)
    negative_prompt: str = Field(default="", max_length=1000)
    steps: int = Field(default=DEFAULT_STEPS, ge=1, le=MAX_STEPS)
    width: int = Field(default=DEFAULT_WIDTH, ge=256, le=MAX_WIDTH)
    height: int = Field(default=DEFAULT_HEIGHT, ge=256, le=MAX_HEIGHT)
    guidance_scale: float = Field(default=7.0, ge=1.0, le=15.0)
    seed: int | None = Field(default=None, ge=0, le=2_147_483_647)


class GenerateResponse(BaseModel):
    images: list[str]
    parameters: dict[str, Any]
    info: str


def _authorized(provided_key: str | None) -> bool:
    if not IMAGE_API_KEY:
        return True
    if not provided_key:
        return False
    return hmac.compare_digest(provided_key, IMAGE_API_KEY)


def _get_pipeline():
    global _pipe
    if _pipe is not None:
        return _pipe

    with _pipe_lock:
        if _pipe is not None:
            return _pipe
        import torch
        from diffusers import DiffusionPipeline

        dtype = torch.float32
        _pipe = DiffusionPipeline.from_pretrained(
            MODEL_ID,
            torch_dtype=dtype,
            safety_checker=None,
        )
        _pipe = _pipe.to("cpu")
        try:
            _pipe.enable_attention_slicing()
        except Exception:
            pass
        return _pipe


def _image_to_data_url(image) -> str:
    buffer = io.BytesIO()
    image.save(buffer, format="PNG", optimize=True)
    encoded = base64.b64encode(buffer.getvalue()).decode("ascii")
    return "data:image/png;base64," + encoded


@app.get("/")
def root():
    return {
        "name": "Game API Image Generation AI",
        "status": "online",
        "model": MODEL_ID,
        "api": "/sdapi/v1/txt2img",
    }


@app.get("/health")
def health():
    return {
        "status": "healthy",
        "model": MODEL_ID,
        "model_loaded": _pipe is not None,
        "authentication": "api-key" if IMAGE_API_KEY else "open",
    }


@app.post("/sdapi/v1/txt2img", response_model=GenerateResponse)
def txt2img(payload: Txt2ImgRequest, x_api_key: str | None = Header(default=None)):
    if not _authorized(x_api_key):
        raise HTTPException(status_code=401, detail="Invalid image engine API key.")

    if not _generation_lock.acquire(blocking=False):
        raise HTTPException(status_code=429, detail="Another image is currently being generated. Please try again shortly.")

    try:
        import torch

        pipe = _get_pipeline()
        generator = None
        if payload.seed is not None:
            generator = torch.Generator(device="cpu").manual_seed(payload.seed)

        result = pipe(
            prompt=payload.prompt,
            negative_prompt=payload.negative_prompt or None,
            num_inference_steps=payload.steps,
            guidance_scale=payload.guidance_scale,
            width=payload.width,
            height=payload.height,
            generator=generator,
        )

        image = result.images[0]
        data_url = _image_to_data_url(image)
        return GenerateResponse(
            images=[data_url],
            parameters=payload.model_dump(),
            info="Generated by the self-hosted Game API image engine.",
        )
    except HTTPException:
        raise
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Image generation failed: {exc}")
    finally:
        _generation_lock.release()
